//! The board file is the single description of the PCB: it must round-trip
//! through JSON, the committed copy must match what the builder makes,
//! and a test-sized variant must differ from it only in the boot wiring.
use mips32::board::{Board, Model, PinKind};
use mips32::cpu::{Params, board};
use std::collections::BTreeSet;

#[test]
fn board_round_trips_through_json() {
    let b = board(&Params::board());
    let j = b.to_json();
    let back = Board::from_json(&j).unwrap();
    assert_eq!(back, b);
}

/// `boards/crag/netlist.json` is generated by `mips32 export crag`; this
/// fails when the design changed and the file was not regenerated.
#[test]
fn committed_board_file_is_current() {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/boards/crag/netlist.json");
    let committed = Board::from_json(&std::fs::read_to_string(path).expect("boards/crag/netlist.json")).unwrap();
    let fresh = board(&Params::board());
    assert_eq!(committed.chips.len(), fresh.chips.len(), "chip count; regenerate with `cargo run --release -- export crag > boards/crag/netlist.json`");
    for (a, b) in committed.chips.iter().zip(&fresh.chips) {
        assert_eq!(a, b, "chip {} differs; regenerate the board file", a.name);
    }
    assert_eq!(committed, fresh, "regenerate the board file");
}

/// Every chip has a part number, a package, a block that the layout
/// places, and every pin a net; every net has at least one pin or a tie.
#[test]
fn board_is_complete() {
    let b = board(&Params::board());
    let placed: BTreeSet<&str> = b.layout.iter().flat_map(|c| c.blocks.iter().map(String::as_str)).collect();
    let mut nets_used: BTreeSet<&str> = BTreeSet::new();
    for c in &b.chips {
        assert!(!c.part.is_empty() && !c.package.is_empty(), "{}", c.name);
        assert!(placed.contains(c.block.as_str()), "{}: block {:?} is not in the layout", c.name, c.block);
        assert!(!c.pins.is_empty(), "{}: no pins", c.name);
        let mut seen = BTreeSet::new();
        for p in &c.pins {
            assert!(seen.insert(p.pin), "{}: pin {} twice", c.name, p.pin);
            assert!(!p.net.is_empty());
            nets_used.insert(p.net.as_str());
            if p.kind == PinKind::Power {
                assert!(p.net == "VCC" || p.net == "GND", "{}: power pin {} on {}", c.name, p.name, p.net);
            }
        }
        if let Model::Gal { pins, eqs, .. } = &c.model {
            // Every equation output and input has a pin.
            let sig: BTreeSet<&str> = pins.iter().map(|(_, s)| s.as_str()).collect();
            for e in eqs {
                assert!(sig.contains(e.out.as_str()), "{}: output {} has no pin", c.name, e.out);
                for t in &e.terms {
                    for (l, _) in t {
                        assert!(sig.contains(l.as_str()), "{}: input {} has no pin", c.name, l);
                    }
                }
            }
        }
    }
    let declared: BTreeSet<&str> = b.nets.iter().map(|n| n.name.as_str()).collect();
    for n in &nets_used {
        assert!(declared.contains(n), "net {n} used but not declared");
    }
    // Every net with a single pin is a tie, a pull, or a known dangling
    // output; list them so a stray one is noticed.
    let mut count = std::collections::BTreeMap::new();
    for c in &b.chips {
        for p in &c.pins {
            *count.entry(p.net.as_str()).or_insert(0) += 1;
        }
    }
    let singles: Vec<&str> = b
        .nets
        .iter()
        .filter(|n| count.get(n.name.as_str()).copied().unwrap_or(0) == 1 && n.tie.is_none() && n.pull.is_none())
        .map(|n| n.name.as_str())
        .collect();
    // A GAL output used only inside its own chip (a counter bit, a state
    // flag) is a legitimate single connection: the chip reads it through
    // its internal feedback.
    let mut internal: BTreeSet<String> = BTreeSet::new();
    for c in &b.chips {
        if let Model::Gal { pins, eqs, .. } = &c.model {
            let reads: BTreeSet<&str> = eqs.iter().flat_map(|e| e.terms.iter().flatten().map(|(l, _)| l.as_str())).collect();
            for e in eqs {
                if reads.contains(e.out.as_str()) {
                    if let Some((p, _)) = pins.iter().find(|(_, sname)| *sname == e.out) {
                        if let Some(pr) = c.pins.iter().find(|pr| pr.pin == *p) {
                            internal.insert(pr.net.clone());
                        }
                    }
                }
            }
        }
    }
    // The bus write qualifier (for a memory card), the unused delay-line
    // taps, and the serial lines to the connector.
    let allowed = |n: &str| {
        internal.contains(n)
            || n == "BWEQ"
            || n.starts_with("T2") || n.starts_with("T4") || n.starts_with("T5")
            || n.starts_with("U2") || n.starts_with("U3") || n.starts_with("U4") || n.starts_with("U5")
            || n == "RS232_TX" || n == "RS232_RX"
    };
    let stray: Vec<&str> = singles.iter().copied().filter(|n| !allowed(n)).collect();
    assert!(stray.is_empty(), "nets with a single connection: {stray:?}");
}

/// A test-sized boot region changes the WRAP tap, the boot address
/// buffer wiring, the NPH / SKIP ties: nothing else.
#[test]
fn test_variant_differs_only_in_boot_wiring() {
    let full = board(&Params::board());
    let small = board(&Params { code_words_log2: 6, data_regions: 2, skip: false, gate_tap: (40, 0) });
    assert_eq!(full.chips.len(), small.chips.len());
    let mut changed = BTreeSet::new();
    for (a, b) in full.chips.iter().zip(&small.chips) {
        assert_eq!(a.name, b.name);
        assert_eq!(a.model, b.model, "{}", a.name);
        for (pa, pb) in a.pins.iter().zip(&b.pins) {
            if pa.net != pb.net {
                changed.insert(a.name.clone());
            }
        }
    }
    for c in &changed {
        assert!(c.starts_with("rom") || c.starts_with("badr") || c.starts_with("bseq"), "{c} changed between the board and the test variant");
    }
    let ties = |b: &Board| -> Vec<(String, Option<mips32::board::Fixed>)> { b.nets.iter().filter(|n| n.name.starts_with("NPH") || n.name == "SKIP").map(|n| (n.name.clone(), n.tie)).collect() };
    assert_ne!(ties(&full), ties(&small));
}
