//! The board description: one serialisable structure that is the PCB
//! netlist, the bill of materials, the GAL equations, and the diagram's
//! layout.  Generated by a builder (see `boards/`), committed as
//! `boards/<name>/netlist.json`, and the only thing the simulator's
//! loader, the chip map, the KiCad export and the JEDEC manifest read.
//!
//! What the file does *not* contain is stimulus: programs, memory images,
//! test-bench choices such as the delay-line tolerance grade, the fast
//! gate's delay range, the supervisor's release phase, or the terminal's
//! input.  Those are [`Load`] options applied when a board is
//! instantiated.

use crate::as7c164a::{self, As7c164a};
use crate::cy7c131::{Cy7c131, Level, Time, NS};
use crate::ds1100::{Ds1100, Grade};
use crate::gal22v10::Gal22v10;
use crate::galpack::{self, Eq};
use crate::netlist::{FastGate, Netlist, Passive, ResetSupervisor, Rom, Sram16};
use crate::uart16550::{BusTiming, Uart16550};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

/// What a pin is, as far as the board is concerned.
#[derive(Clone, Copy, PartialEq, Eq, Debug, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum PinKind {
    In,
    Out,
    Bidir,
    Power,
    /// A passive part's terminal.
    Passive,
    /// No internal connection.
    Nc,
}

/// How to build the simulation model of a chip.
#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum Model {
    /// ATF22V10C: the equations and which signal each pin carries (the
    /// signal names of the equations; the pin list has the board net,
    /// which differs where nets were merged after packing).
    Gal { clk: Option<String>, ar: Option<String>, eqs: Vec<Eq>, pins: Vec<(usize, String)> },
    /// 8K x 8 SRAM (instruction memory lanes).
    Sram8k { timing: String },
    /// 256K x 16 SRAM (data memory halves).
    Sram16 { timing: String },
    /// CY7C131 1K x 8 dual-port (register file).
    DualPort1k { timing: String },
    /// DS1100 delay line.
    Ds1100 { total_ns: u32 },
    /// Single fast NAND gate.
    Gate,
    /// Reset supervisor.
    Supervisor,
    /// Flash / EEPROM.
    Rom { tacc_ns: u32, toe_ns: u32, tdf_ns: u32 },
    /// 16550 UART with its crystal.
    Uart { xin_hz: f64 },
    /// No model: transceivers, crystals, capacitors, connectors.
    Passive,
}

#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub struct PinRec {
    pub pin: usize,
    pub name: String,
    pub net: String,
    pub kind: PinKind,
}

#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub struct ChipRec {
    pub name: String,
    /// Orderable part number.
    pub part: String,
    pub package: String,
    /// Diagram block and pipeline stage.
    pub block: String,
    pub stage: String,
    /// What the loader needs to find it by: "rf:<bank><lane>",
    /// "imem:<lane>", "rom:<lane>", "dmem:<half>", "uart", ...
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    pub model: Model,
    /// LCSC part number for the JLCPCB bill of materials; absent while
    /// the part is still to be sourced.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lcsc: Option<String>,
    pub pins: Vec<PinRec>,
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Fixed {
    High,
    Low,
}

#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub struct NetRec {
    pub name: String,
    /// Wired to a rail.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tie: Option<Fixed>,
    /// Pull resistor.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pull: Option<Fixed>,
    /// "clk", "reset", "reset_button", "pc:<bit>" ...
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
}

/// One column of the chip map.
#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub struct Column {
    pub title: String,
    pub width: u32,
    pub blocks: Vec<String>,
    #[serde(default)]
    pub reg: bool,
}

#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub struct Board {
    pub name: String,
    pub description: String,
    /// Nominal clock period.
    pub period_ns: f64,
    /// Design parameters the wiring depends on (region size, ...).
    #[serde(default)]
    pub params: BTreeMap<String, serde_json::Value>,
    pub layout: Vec<Column>,
    pub chips: Vec<ChipRec>,
    pub nets: Vec<NetRec>,
    /// What each bus (a net name without its bit index) is, for the chip
    /// map.  Empty: the map falls back to its own table.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub bus_descriptions: BTreeMap<String, String>,
}

/// Metadata a builder attaches to every chip it adds to a [`Netlist`].
#[derive(Clone, Debug)]
pub struct ChipMeta {
    pub part: String,
    pub package: String,
    pub block: String,
    pub stage: String,
    pub role: Option<String>,
    pub model: Model,
    /// LCSC part number, for the JLCPCB bill of materials.  None for a
    /// part still to be sourced.
    pub lcsc: Option<String>,
}

/// Test-bench choices made when a board is instantiated.
#[derive(Clone, Debug)]
pub struct Load {
    pub grade: Grade,
    /// Fast gate delay range (ps).
    pub gate_tpd: (Time, Time),
    /// When the supervisor releases RST_n (ps from power-on).
    pub reset_release: Time,
    pub mr_timeout: Time,
    /// Overrides the board crystal.
    pub uart_xin_hz: Option<f64>,
    /// Data memory timing override (a part sweep).
    pub dmem_timing: Option<as7c164a::Timing>,
}

impl Board {
    pub fn to_json(&self) -> String {
        serde_json::to_string_pretty(self).expect("serialise board")
    }
    pub fn from_json(s: &str) -> Result<Board, serde_json::Error> {
        serde_json::from_str(s)
    }

    pub fn chip(&self, name: &str) -> Option<&ChipRec> {
        self.chips.iter().find(|c| c.name == name)
    }
    pub fn by_role(&self, role: &str) -> Option<&ChipRec> {
        self.chips.iter().find(|c| c.role.as_deref() == Some(role))
    }
    pub fn param_u64(&self, key: &str) -> Option<u64> {
        self.params.get(key).and_then(|v| v.as_u64())
    }
    pub fn param_bool(&self, key: &str) -> Option<bool> {
        self.params.get(key).and_then(|v| v.as_bool())
    }

    /// Build the simulation netlist: a model per chip from its record,
    /// every connection, every tie and pull.
    pub fn instantiate(&self, load: &Load) -> Netlist {
        let mut nl = Netlist::new();
        for c in &self.chips {
            let meta = ChipMeta { part: c.part.clone(), package: c.package.clone(), block: c.block.clone(), stage: c.stage.clone(), role: c.role.clone(), model: c.model.clone(), lcsc: c.lcsc.clone() };
            let id = match &c.model {
                Model::Gal { clk, ar, eqs, pins } => {
                    let spec = galpack::GalSpec { name: c.name.clone(), clk: clk.clone(), ar: ar.clone(), eqs: eqs.clone() };
                    let cfg = galpack::configure(&spec, pins);
                    nl.add_chip(&c.name, Gal22v10::new(cfg))
                }
                Model::Sram8k { timing } => nl.add_chip(&c.name, As7c164a::with_timing(as7c164a::Timing::by_name(timing))),
                Model::Sram16 { timing } => {
                    let t = load.dmem_timing.unwrap_or_else(|| as7c164a::Timing::by_name(timing));
                    nl.add_chip(&c.name, Sram16::new(t))
                }
                Model::DualPort1k { timing } => nl.add_chip(&c.name, Cy7c131::with_timing(crate::cy7c131::Timing::by_name(timing))),
                Model::Ds1100 { total_ns } => nl.add_chip(&c.name, Ds1100::new(*total_ns, load.grade)),
                Model::Gate => nl.add_chip(&c.name, FastGate::new(load.gate_tpd.0, load.gate_tpd.1)),
                Model::Supervisor => nl.add_chip(&c.name, ResetSupervisor::new(load.reset_release, load.mr_timeout)),
                Model::Rom { tacc_ns, toe_ns, tdf_ns } => nl.add_chip(&c.name, Rom::new(*tacc_ns as Time * NS, *toe_ns as Time * NS, *tdf_ns as Time * NS)),
                Model::Uart { xin_hz } => nl.add_chip(&c.name, Uart16550::new(BusTiming::tl16c550c(), load.uart_xin_hz.unwrap_or(*xin_hz))),
                Model::Passive => {
                    let names: Vec<(usize, String)> = c.pins.iter().map(|p| (p.pin, p.name.clone())).collect();
                    nl.add_chip(&c.name, Passive::new(names))
                }
            };
            nl.set_meta(id, meta);
            for p in &c.pins {
                let net = nl.net(&p.net);
                nl.connect(net, id, p.pin);
            }
        }
        for n in &self.nets {
            let id = nl.net(&n.name);
            if let Some(t) = n.tie {
                nl.tie(id, if t == Fixed::High { Level::H } else { Level::L });
            }
            if let Some(p) = n.pull {
                nl.pull(id, if p == Fixed::High { Level::H } else { Level::L });
            }
            if let Some(r) = &n.role {
                nl.set_net_role(id, r);
            }
        }
        nl
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn json_round_trip() {
        let b = Board {
            name: "t".into(),
            description: String::new(),
            period_ns: 34.0,
            params: [("k".to_string(), serde_json::json!(13))].into_iter().collect(),
            layout: vec![Column { title: "IF".into(), width: 100, blocks: vec!["PC".into()], reg: false }],
            chips: vec![ChipRec {
                name: "x0".into(),
                part: "ATF22V10C-7PX".into(),
                package: "DIP-24".into(),
                block: "PC".into(),
                stage: "IF".into(),
                role: None,
                model: Model::Gal { clk: Some("CLK".into()), ar: None, eqs: vec![Eq::sop("Q", galpack::Mode::Reg, vec![vec![("A".into(), true)]])], pins: vec![(1, "CLK".into())] },
                pins: vec![PinRec { pin: 1, name: "CLK".into(), net: "CLK".into(), kind: PinKind::In }],
            }],
            nets: vec![NetRec { name: "CLK".into(), tie: None, pull: None, role: Some("clk".into()) }],
            bus_descriptions: BTreeMap::new(),
        };
        let j = b.to_json();
        assert_eq!(Board::from_json(&j).unwrap(), b);
    }
}
